---
apiVersion: v1
kind: Service
metadata:
  name: foo-controller-local
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  labels:
    app: foo-controller
spec:
 type: ClusterIP
 ports:
 - name: http
   port: 8080
   targetPort: 8080
   protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
 name: foo-controller-local
 namespace: default
subsets:
- addresses:
    - ip: 192.168.1.246
  ports:
    - port: 8080
      name: http
